// This file was generated by SquareLine Studio, then restyled for the kid UI.

#include <stdint.h>

#include "../ui.h"
#include "../ui_kid_style.h"

typedef enum {
    MAIN_TOPIC_YUWEN = 0,
    MAIN_TOPIC_SHUXUE,
    MAIN_TOPIC_YINGYU,
    MAIN_TOPIC_AI,
    MAIN_TOPIC_DONGHUA,
    MAIN_TOPIC_SETTING,
} main_topic_t;

typedef enum {
    MAIN_ACTION_1 = 0,
    MAIN_ACTION_2,
    MAIN_ACTION_3,
} main_action_t;

static main_topic_t g_topic = MAIN_TOPIC_YUWEN;
static lv_obj_t *g_cards[6];
static lv_obj_t *g_right_title;
static lv_obj_t *g_right_btns[3];
static lv_obj_t *g_right_labels[3];

extern void Btnguoxuetangshi_event_handler(lv_event_t *e);
extern void Btnsanzijing_event_handler(lv_event_t *e);
extern void Btnjiafayunsuan_event_handler(lv_event_t *e);
extern void Btnjianfayunsuan_event_handler(lv_event_t *e);
extern void Btnrenshizimu_event_handler(lv_event_t *e);
extern void Btnquweidanci_event_handler(lv_event_t *e);
extern void Btntonghuagushi_event_handler(lv_event_t *e);
extern void Btnzhishibaike_event_handler(lv_event_t *e);
extern void Btnchangchangyingyu_event_handler(lv_event_t *e);
extern void Btnxiaozhupeiqi_event_handler(lv_event_t *e);
extern void Btnxitongshengji_event_handler(lv_event_t *e);
extern void Btnwifishezhi_event_handler(lv_event_t *e);

static void set_card_checked(lv_obj_t *card, bool checked)
{
    lv_obj_set_style_border_width(card, checked ? 2 : 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(card, lv_color_hex(0xA9C7FF), LV_PART_MAIN | LV_STATE_DEFAULT);
}

static lv_obj_t *make_card(lv_obj_t *parent, lv_obj_t **label, const char *title, const char *sub,
                           lv_coord_t x, lv_coord_t y, uint32_t color, main_topic_t topic)
{
    (void)sub;

    lv_obj_t *btn = lv_btn_create(parent);
    lv_obj_set_width(btn, 98);
    lv_obj_set_height(btn, 56);
    lv_obj_set_x(btn, x);
    lv_obj_set_y(btn, y);
    lv_obj_set_align(btn, LV_ALIGN_TOP_LEFT);
    kid_btn_style(btn, color);

    *label = kid_label(btn, title, 0, 0, 98, 0x20304A);
    lv_obj_set_height(*label, LV_SIZE_CONTENT);
    lv_obj_align(*label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_style_text_align(*label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    g_cards[topic] = btn;
    return btn;
}

static lv_obj_t *make_right_btn(lv_obj_t *parent, lv_obj_t **label, lv_coord_t y)
{
    lv_obj_t *btn = lv_btn_create(parent);
    lv_obj_set_width(btn, 104);
    lv_obj_set_height(btn, 38);
    lv_obj_set_x(btn, 9);
    lv_obj_set_y(btn, y);
    lv_obj_set_align(btn, LV_ALIGN_TOP_LEFT);
    kid_btn_style(btn, 0xFFFFFF);
    lv_obj_set_style_shadow_width(btn, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(btn, 45, LV_PART_MAIN | LV_STATE_DEFAULT);

    *label = kid_label(btn, "", 9, 10, 74, 0x20304A);
    kid_label(btn, ">", 86, 10, 12, 0x5F86B6);
    return btn;
}

static void update_right_menu(void)
{
    static const char *title[] = {
        "语文宝藏", "数学运算", "英语启蒙", "智能AI", "趣味游戏", "系统设置"
    };
    static const char *items[][3] = {
        {"国学唐诗", "三字经", ""},
        {"数字运算", "认识图形", ""},
        {"认识字母", "趣味单词", ""},
        {"输入IP", "AI Chat", ""},
        {"贪吃蛇", "2048", ""},
        {"系统升级", "Wi-Fi设置", ""},
    };

    lv_label_set_text(g_right_title, title[g_topic]);
    for (int i = 0; i < 2; i++) {
        lv_label_set_text(g_right_labels[i], items[g_topic][i]);
    }
    for (int i = 0; i < 6; i++) {
        set_card_checked(g_cards[i], i == g_topic);
    }
}

static void select_topic_cb(lv_event_t *e)
{
    if (lv_event_get_code(e) != LV_EVENT_CLICKED) {
        return;
    }

    g_topic = (main_topic_t)(uintptr_t)lv_event_get_user_data(e);
    update_right_menu();
}

static void enter_topic_cb(lv_event_t *e)
{
    if (lv_event_get_code(e) != LV_EVENT_CLICKED) {
        return;
    }

    main_action_t action = (main_action_t)(uintptr_t)lv_event_get_user_data(e);

    switch (g_topic) {
    case MAIN_TOPIC_YUWEN:
        ui_event_Btnyuwenbaozang(e);
        if (action == MAIN_ACTION_1) {
            Btnguoxuetangshi_event_handler(e);
        } else if (action == MAIN_ACTION_2) {
            Btnsanzijing_event_handler(e);
        }
        break;
    case MAIN_TOPIC_SHUXUE:
        ui_event_Btnshuxueyunsuan(e);
        if (action == MAIN_ACTION_1) {
            Btnjiafayunsuan_event_handler(e);
        } else if (action == MAIN_ACTION_2) {
            Btnjianfayunsuan_event_handler(e);
        }
        break;
    case MAIN_TOPIC_YINGYU:
        ui_event_Btnyingyuqimeng(e);
        if (action == MAIN_ACTION_1) {
            Btnrenshizimu_event_handler(e);
        } else if (action == MAIN_ACTION_2) {
            Btnquweidanci_event_handler(e);
        }
        break;
    case MAIN_TOPIC_AI:
        ui_event_Btnzhinengai(e);
        if (action == MAIN_ACTION_1) {
            Btntonghuagushi_event_handler(e);
        } else if (action == MAIN_ACTION_2) {
            Btnzhishibaike_event_handler(e);
        }
        break;
    case MAIN_TOPIC_DONGHUA:
        ui_event_Btnquweidonghua(e);
        if (action == MAIN_ACTION_1) {
            Btnchangchangyingyu_event_handler(e);
        } else if (action == MAIN_ACTION_2) {
            Btnxiaozhupeiqi_event_handler(e);
        }
        break;
    case MAIN_TOPIC_SETTING:
        ui_event_Btnxitongshezhi(e);
        if (action == MAIN_ACTION_1) {
            Btnxitongshengji_event_handler(e);
        } else if (action == MAIN_ACTION_2) {
            Btnwifishezhi_event_handler(e);
        }
        break;
    default:
        break;
    }
}

void ui_mainscreen_screen_init(void)
{
    ui_mainscreen = lv_obj_create(NULL);
    kid_screen_style(ui_mainscreen);

    ui_Bg = lv_obj_create(ui_mainscreen);
    lv_obj_set_width(ui_Bg, 464);
    lv_obj_set_height(ui_Bg, 256);
    lv_obj_set_align(ui_Bg, LV_ALIGN_CENTER);
    kid_card_style(ui_Bg, 0xFFFFFF, 0xE7EEF5);

    lv_obj_t *left = lv_obj_create(ui_mainscreen);
    lv_obj_set_width(left, 94);
    lv_obj_set_height(left, 232);
    lv_obj_set_x(left, 16);
    lv_obj_set_y(left, 20);
    lv_obj_set_align(left, LV_ALIGN_TOP_LEFT);
    kid_card_style(left, 0xFFF1D6, 0);
    kid_label(left, "欢迎回来", 12, 14, 70, 0x20304A);
    kid_label(left, "学习乐园", 12, 40, 70, 0x56677F);
    kid_label(left, "今天想去", 12, 170, 70, 0x56677F);
    kid_label(left, "哪个小岛", 12, 194, 70, 0x56677F);

    ui_LabelTitle = kid_label(ui_mainscreen, "学习星球", 144, 24, 160, 0x20304A);

    ui_Btnyuwenbaozang = make_card(ui_mainscreen, &ui_Label1, "语文宝藏", "三字经", 126, 60, 0xFFDDB4, MAIN_TOPIC_YUWEN);
    ui_Btnshuxueyunsuan = make_card(ui_mainscreen, &ui_Label4, "数学运算", "加法减法", 232, 60, 0xFFB5C3, MAIN_TOPIC_SHUXUE);
    ui_Btnyingyuqimeng = make_card(ui_mainscreen, &ui_Label5, "英语启蒙", "字母单词", 126, 124, 0xB7C8FF, MAIN_TOPIC_YINGYU);
    ui_Btnzhinengai = make_card(ui_mainscreen, &ui_Label2, "智能AI", "童话百科", 232, 124, 0xFFF96E, MAIN_TOPIC_AI);
    ui_Btnquweidonghua = make_card(ui_mainscreen, &ui_Label3, "趣味游戏", "贪吃蛇", 126, 188, 0x50E67F, MAIN_TOPIC_DONGHUA);
    ui_Btnxitongshezhi = make_card(ui_mainscreen, &ui_Label6, "系统设置", "升级网络", 232, 188, 0xFFC1DC, MAIN_TOPIC_SETTING);

    lv_obj_t *right = lv_obj_create(ui_mainscreen);
    lv_obj_set_width(right, 122);
    lv_obj_set_height(right, 232);
    lv_obj_set_x(right, 346);
    lv_obj_set_y(right, 20);
    lv_obj_set_align(right, LV_ALIGN_TOP_LEFT);
    kid_card_style(right, 0xFFFFFF, 0);

    lv_obj_t *tip = lv_obj_create(right);
    lv_obj_set_width(tip, 112);
    lv_obj_set_height(tip, 80);
    lv_obj_set_x(tip, 5);
    lv_obj_set_y(tip, 0);
    lv_obj_set_align(tip, LV_ALIGN_TOP_LEFT);
    kid_card_style(tip, 0xFFF6D8, 0xF9D873);
    lv_obj_set_style_shadow_width(tip, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    kid_label(tip, "当前小岛", 7, 8, 98, 0x56677F);
    g_right_title = kid_label(tip, "", 7, 36, 98, 0x20304A);
    lv_obj_set_style_text_align(g_right_title, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    g_right_btns[0] = make_right_btn(right, &g_right_labels[0], 100);
    g_right_btns[1] = make_right_btn(right, &g_right_labels[1], 156);
    g_right_btns[2] = make_right_btn(right, &g_right_labels[2], 186);
    lv_obj_add_flag(g_right_btns[2], LV_OBJ_FLAG_HIDDEN);

    lv_obj_add_event_cb(ui_Btnyuwenbaozang, select_topic_cb, LV_EVENT_ALL, (void *)MAIN_TOPIC_YUWEN);
    lv_obj_add_event_cb(ui_Btnshuxueyunsuan, select_topic_cb, LV_EVENT_ALL, (void *)MAIN_TOPIC_SHUXUE);
    lv_obj_add_event_cb(ui_Btnyingyuqimeng, select_topic_cb, LV_EVENT_ALL, (void *)MAIN_TOPIC_YINGYU);
    lv_obj_add_event_cb(ui_Btnzhinengai, select_topic_cb, LV_EVENT_ALL, (void *)MAIN_TOPIC_AI);
    lv_obj_add_event_cb(ui_Btnquweidonghua, select_topic_cb, LV_EVENT_ALL, (void *)MAIN_TOPIC_DONGHUA);
    lv_obj_add_event_cb(ui_Btnxitongshezhi, select_topic_cb, LV_EVENT_ALL, (void *)MAIN_TOPIC_SETTING);

    for (int i = 0; i < 3; i++) {
        lv_obj_add_event_cb(g_right_btns[i], enter_topic_cb, LV_EVENT_ALL, (void *)(uintptr_t)i);
    }

    update_right_menu();
}
