// This file was generated by SquareLine Studio, then restyled for the kid UI.

#include "../ui.h"
#include "../ui_kid_style.h"

void ui_quweidonghua_screen_init(void)
{
    ui_quweidonghua = lv_obj_create(NULL);
    kid_screen_style(ui_quweidonghua);

    ui_Bg2 = lv_obj_create(ui_quweidonghua);
    lv_obj_set_width(ui_Bg2, 464);
    lv_obj_set_height(ui_Bg2, 256);
    lv_obj_set_align(ui_Bg2, LV_ALIGN_CENTER);
    kid_card_style(ui_Bg2, 0xFFFFFF, 0xE7EEF5);

    kid_page_title(ui_quweidonghua, &ui_LabelTitle2, "趣味游戏");

    ui_Btnchangchangyingyu = lv_btn_create(ui_quweidonghua);
    kid_list_btn(ui_Btnchangchangyingyu, &ui_Label8, "贪吃蛇", 16, 116, 126);
    lv_obj_add_flag(ui_Btnchangchangyingyu, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_HIDDEN);

    ui_Btnxiaozhupeiqi = lv_btn_create(ui_quweidonghua);
    kid_list_btn(ui_Btnxiaozhupeiqi, &ui_Label9, "2048", 16, 166, 126);
    lv_obj_add_flag(ui_Btnxiaozhupeiqi, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_HIDDEN);

    ui_Btnfanhuizhuye1 = lv_btn_create(ui_quweidonghua);
    kid_small_back_btn(ui_Btnfanhuizhuye1, &ui_Label12);

    ui_TabViewquweidonghua = lv_tabview_create(ui_quweidonghua, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_TabViewquweidonghua, 300);
    lv_obj_set_height(ui_TabViewquweidonghua, 200);
    lv_obj_set_x(ui_TabViewquweidonghua, 60);
    lv_obj_set_y(ui_TabViewquweidonghua, 21);
    lv_obj_set_align(ui_TabViewquweidonghua, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TabViewquweidonghua, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_TabViewquweidonghua, LV_OBJ_FLAG_SCROLLABLE);

    ui_Imagequweidonghua = lv_img_create(ui_quweidonghua);
    kid_content_image_style(ui_Imagequweidonghua);
    lv_obj_set_width(ui_Imagequweidonghua, 360);
    lv_obj_set_height(ui_Imagequweidonghua, 224);
    lv_obj_set_y(ui_Imagequweidonghua, 24);
    lv_obj_add_flag(ui_Imagequweidonghua, LV_OBJ_FLAG_ADV_HITTEST);

    lv_obj_add_event_cb(ui_Btnchangchangyingyu, ui_event_Btnchangchangyingyu, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Btnxiaozhupeiqi, ui_event_Btnxiaozhupeiqi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Btnfanhuizhuye1, ui_event_Btnfanhuizhuye1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_quweidonghua, ui_event_quweidonghua, LV_EVENT_ALL, NULL);
}
