// This file was generated by SquareLine Studio, then restyled for the kid UI.

#include "../ui.h"
#include "../ui_kid_style.h"

extern void MathShapeNext_event_handler(lv_event_t *e);

static void math_keyboard_event_cb(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);

    if (code == LV_EVENT_READY || code == LV_EVENT_CANCEL) {
        lv_obj_add_flag(ui_KeyboardMathAnswer, LV_OBJ_FLAG_HIDDEN);
    }
}

static void math_answer_event_cb(lv_event_t *e)
{
    if (lv_event_get_code(e) == LV_EVENT_FOCUSED) {
        lv_keyboard_set_textarea(ui_KeyboardMathAnswer, ui_TextareaMathAnswer);
        lv_obj_clear_flag(ui_KeyboardMathAnswer, LV_OBJ_FLAG_HIDDEN);
        lv_obj_move_foreground(ui_KeyboardMathAnswer);
    }
}

void ui_shuxueyunsuan_screen_init(void)
{
    ui_shuxueyunsuan = lv_obj_create(NULL);
    kid_screen_style(ui_shuxueyunsuan);

    ui_Bg5 = lv_obj_create(ui_shuxueyunsuan);
    lv_obj_set_width(ui_Bg5, 464);
    lv_obj_set_height(ui_Bg5, 256);
    lv_obj_set_align(ui_Bg5, LV_ALIGN_CENTER);
    kid_card_style(ui_Bg5, 0xFFFFFF, 0xE7EEF5);

    kid_page_title(ui_shuxueyunsuan, &ui_LabelTitle5, "数字运算");

    ui_Btnjiafayunsuan = lv_btn_create(ui_shuxueyunsuan);
    kid_list_btn(ui_Btnjiafayunsuan, &ui_Label19, "数字运算", 16, 116, 126);
    lv_obj_add_flag(ui_Btnjiafayunsuan, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_HIDDEN);

    ui_Btnjianfayunsuan = lv_btn_create(ui_shuxueyunsuan);
    kid_list_btn(ui_Btnjianfayunsuan, &ui_Label20, "认识图形", 16, 166, 126);
    lv_obj_add_flag(ui_Btnjianfayunsuan, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_HIDDEN);

    ui_Btnfanhuizhuye4 = lv_btn_create(ui_shuxueyunsuan);
    kid_small_back_btn(ui_Btnfanhuizhuye4, &ui_Label21);

    ui_TabViezhinengai2 = lv_obj_create(ui_shuxueyunsuan);
    lv_obj_set_width(ui_TabViezhinengai2, 444);
    lv_obj_set_height(ui_TabViezhinengai2, 206);
    lv_obj_set_x(ui_TabViezhinengai2, 18);
    lv_obj_set_y(ui_TabViezhinengai2, 48);
    lv_obj_set_align(ui_TabViezhinengai2, LV_ALIGN_TOP_LEFT);
    kid_card_style(ui_TabViezhinengai2, 0xFFF6D8, 0xF9D873);

    ui_Label27 = kid_label(ui_shuxueyunsuan, "固定100以内加减法", 46, 64, 390, 0x56677F);
    lv_obj_set_style_text_align(ui_Label27, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label28 = kid_label(ui_shuxueyunsuan, "点击重新出题开始", 46, 94, 390, 0x20304A);
    lv_obj_set_style_text_align(ui_Label28, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextareaMathAnswer = lv_textarea_create(ui_shuxueyunsuan);
    lv_obj_set_width(ui_TextareaMathAnswer, 150);
    lv_obj_set_height(ui_TextareaMathAnswer, 38);
    lv_obj_set_x(ui_TextareaMathAnswer, 165);
    lv_obj_set_y(ui_TextareaMathAnswer, 126);
    lv_obj_set_align(ui_TextareaMathAnswer, LV_ALIGN_TOP_LEFT);
    lv_textarea_set_one_line(ui_TextareaMathAnswer, true);
    lv_textarea_set_max_length(ui_TextareaMathAnswer, 4);
    lv_textarea_set_placeholder_text(ui_TextareaMathAnswer, "输入答案");
    lv_obj_add_event_cb(ui_TextareaMathAnswer, math_answer_event_cb, LV_EVENT_ALL, NULL);

    ui_Dropdownmaxnum = lv_dropdown_create(ui_shuxueyunsuan);
    lv_dropdown_set_options(ui_Dropdownmaxnum, "100");
    lv_obj_set_width(ui_Dropdownmaxnum, 68);
    lv_obj_set_height(ui_Dropdownmaxnum, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Dropdownmaxnum, 220);
    lv_obj_set_y(ui_Dropdownmaxnum, 58);
    lv_obj_set_align(ui_Dropdownmaxnum, LV_ALIGN_TOP_LEFT);
    lv_obj_add_flag(ui_Dropdownmaxnum, LV_OBJ_FLAG_HIDDEN);

    ui_Btnchongxinchuti = lv_btn_create(ui_shuxueyunsuan);
    kid_menu_btn(ui_Btnchongxinchuti, &ui_Label25, "重新出题", 116, 178, 0xFFF2A0);

    ui_Btnchakandaan = lv_btn_create(ui_shuxueyunsuan);
    kid_menu_btn(ui_Btnchakandaan, &ui_Label26, "结果验证", 264, 178, 0xFFFFFF);

    ui_Imageshuxueyunsuan = lv_img_create(ui_shuxueyunsuan);
    kid_content_image_style(ui_Imageshuxueyunsuan);
    lv_obj_add_flag(ui_Imageshuxueyunsuan, LV_OBJ_FLAG_ADV_HITTEST | LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_HIDDEN);

    ui_KeyboardMathAnswer = lv_keyboard_create(ui_shuxueyunsuan);
    lv_obj_set_width(ui_KeyboardMathAnswer, 300);
    lv_obj_set_height(ui_KeyboardMathAnswer, 104);
    lv_obj_set_x(ui_KeyboardMathAnswer, 90);
    lv_obj_set_y(ui_KeyboardMathAnswer, 154);
    lv_obj_set_align(ui_KeyboardMathAnswer, LV_ALIGN_TOP_LEFT);
    lv_keyboard_set_textarea(ui_KeyboardMathAnswer, ui_TextareaMathAnswer);
    lv_keyboard_set_mode(ui_KeyboardMathAnswer, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_add_event_cb(ui_KeyboardMathAnswer, math_keyboard_event_cb, LV_EVENT_ALL, NULL);
    lv_obj_add_flag(ui_KeyboardMathAnswer, LV_OBJ_FLAG_HIDDEN);

    lv_obj_add_event_cb(ui_Btnjiafayunsuan, ui_event_Btnjiafayunsuan, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Btnjianfayunsuan, ui_event_Btnjianfayunsuan, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Btnfanhuizhuye4, ui_event_Btnfanhuizhuye4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Btnchongxinchuti, ui_event_Btnchongxinchuti, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Btnchakandaan, ui_event_Btnchakandaan, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Dropdownmaxnum, ui_event_Dropdownmaxnum, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Imageshuxueyunsuan, MathShapeNext_event_handler, LV_EVENT_CLICKED, NULL);
}
