// This file was generated by SquareLine Studio, then restyled for the kid UI.

#include "../ui.h"
#include "../ui_kid_style.h"

void ui_xitongshezhi_screen_init(void)
{
    ui_xitongshezhi = lv_obj_create(NULL);
    kid_screen_style(ui_xitongshezhi);

    ui_Bg1 = lv_obj_create(ui_xitongshezhi);
    lv_obj_set_width(ui_Bg1, 464);
    lv_obj_set_height(ui_Bg1, 256);
    lv_obj_set_align(ui_Bg1, LV_ALIGN_CENTER);
    kid_card_style(ui_Bg1, 0xFFFFFF, 0xE7EEF5);

    kid_page_title(ui_xitongshezhi, &ui_LabelTitle1, "系统设置");

    ui_Btnxitongshengji = lv_btn_create(ui_xitongshezhi);
    kid_list_btn(ui_Btnxitongshengji, &ui_Label7, "系统升级", 16, 116, 126);
    lv_obj_add_flag(ui_Btnxitongshengji, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_HIDDEN);

    ui_Btnwifishezhi = lv_btn_create(ui_xitongshezhi);
    kid_list_btn(ui_Btnwifishezhi, &ui_Label10, "Wi-Fi设置", 16, 166, 126);
    lv_obj_add_flag(ui_Btnwifishezhi, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_HIDDEN);

    ui_Btnfanhuizhuye = lv_btn_create(ui_xitongshezhi);
    kid_small_back_btn(ui_Btnfanhuizhuye, &ui_Label11);

    ui_TabViewxitongshezhi = lv_obj_create(ui_xitongshezhi);
    lv_obj_set_width(ui_TabViewxitongshezhi, 444);
    lv_obj_set_height(ui_TabViewxitongshezhi, 206);
    lv_obj_set_x(ui_TabViewxitongshezhi, 18);
    lv_obj_set_y(ui_TabViewxitongshezhi, 48);
    lv_obj_set_align(ui_TabViewxitongshezhi, LV_ALIGN_TOP_LEFT);
    kid_card_style(ui_TabViewxitongshezhi, 0xFFFFFF, 0);

    ui_Label29 = kid_label(ui_xitongshezhi, "点击系统升级查看版本信息", 40, 72, 390, 0x56677F);
    ui_Label30 = kid_label(ui_xitongshezhi, "", 40, 96, 390, 0x20304A);

    ui_Label31 = kid_label(ui_xitongshezhi, "扫描Wi-Fi", 36, 62, 92, 0x20304A);
    lv_obj_add_flag(ui_Label31, LV_OBJ_FLAG_CLICKABLE);

    ui_Dropdownwifilist = lv_dropdown_create(ui_xitongshezhi);
    lv_dropdown_set_options(ui_Dropdownwifilist, "Please Scan");
    lv_obj_set_width(ui_Dropdownwifilist, 248);
    lv_obj_set_height(ui_Dropdownwifilist, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Dropdownwifilist, 132);
    lv_obj_set_y(ui_Dropdownwifilist, 56);
    lv_obj_set_align(ui_Dropdownwifilist, LV_ALIGN_TOP_LEFT);
    lv_obj_add_flag(ui_Dropdownwifilist, LV_OBJ_FLAG_SCROLL_ON_FOCUS);

    ui_Label32 = kid_label(ui_xitongshezhi, "Wi-Fi密码", 36, 108, 92, 0x20304A);

    ui_textareainputpasswod = lv_textarea_create(ui_xitongshezhi);
    lv_obj_set_width(ui_textareainputpasswod, 248);
    lv_obj_set_height(ui_textareainputpasswod, 36);
    lv_obj_set_x(ui_textareainputpasswod, 132);
    lv_obj_set_y(ui_textareainputpasswod, 100);
    lv_obj_set_align(ui_textareainputpasswod, LV_ALIGN_TOP_LEFT);
    lv_textarea_set_max_length(ui_textareainputpasswod, 32);
    lv_textarea_set_placeholder_text(ui_textareainputpasswod, "Input Passwd");
    lv_textarea_set_one_line(ui_textareainputpasswod, true);
    lv_textarea_set_password_mode(ui_textareainputpasswod, true);

    ui_Switchpasswordmode = lv_switch_create(ui_xitongshezhi);
    lv_obj_set_width(ui_Switchpasswordmode, 42);
    lv_obj_set_height(ui_Switchpasswordmode, 24);
    lv_obj_set_x(ui_Switchpasswordmode, 394);
    lv_obj_set_y(ui_Switchpasswordmode, 106);
    lv_obj_set_align(ui_Switchpasswordmode, LV_ALIGN_TOP_LEFT);

    ui_Keyboardwifipasswordinput = lv_keyboard_create(ui_xitongshezhi);
    lv_obj_set_width(ui_Keyboardwifipasswordinput, 412);
    lv_obj_set_height(ui_Keyboardwifipasswordinput, 88);
    lv_obj_set_x(ui_Keyboardwifipasswordinput, 34);
    lv_obj_set_y(ui_Keyboardwifipasswordinput, 154);
    lv_obj_set_align(ui_Keyboardwifipasswordinput, LV_ALIGN_TOP_LEFT);

    lv_obj_add_event_cb(ui_Btnxitongshengji, ui_event_Btnxitongshengji, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Btnwifishezhi, ui_event_Btnwifishezhi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Btnfanhuizhuye, ui_event_Btnfanhuizhuye, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboardwifipasswordinput, ui_textareainputpasswod);
    lv_obj_add_event_cb(ui_Keyboardwifipasswordinput, ui_event_Keyboardwifipasswordinput, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Label31, ui_event_Label31, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switchpasswordmode, ui_event_Switchpasswordmode, LV_EVENT_ALL, NULL);
}
