// This file was generated by SquareLine Studio, then restyled for the kid UI.

#include "../ui.h"
#include "../ui_kid_style.h"

void ui_yingyuqimeng_screen_init(void)
{
    ui_yingyuqimeng = lv_obj_create(NULL);
    kid_screen_style(ui_yingyuqimeng);

    ui_Bg6 = lv_obj_create(ui_yingyuqimeng);
    lv_obj_set_width(ui_Bg6, 464);
    lv_obj_set_height(ui_Bg6, 256);
    lv_obj_set_align(ui_Bg6, LV_ALIGN_CENTER);
    kid_card_style(ui_Bg6, 0xFFFFFF, 0xE7EEF5);

    kid_page_title(ui_yingyuqimeng, &ui_LabelTitle6, "英语启蒙");

    ui_Btnrenshizimu = lv_btn_create(ui_yingyuqimeng);
    kid_list_btn(ui_Btnrenshizimu, &ui_Label22, "认识字母", 16, 116, 126);
    lv_obj_add_flag(ui_Btnrenshizimu, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_HIDDEN);

    ui_Btnquweidanci = lv_btn_create(ui_yingyuqimeng);
    kid_list_btn(ui_Btnquweidanci, &ui_Label23, "趣味单词", 16, 166, 126);
    lv_obj_add_flag(ui_Btnquweidanci, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_HIDDEN);

    ui_Btnfanhuizhuye5 = lv_btn_create(ui_yingyuqimeng);
    kid_small_back_btn(ui_Btnfanhuizhuye5, &ui_Label24);

    ui_TabViezhinengai3 = lv_tabview_create(ui_yingyuqimeng, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_TabViezhinengai3, 300);
    lv_obj_set_height(ui_TabViezhinengai3, 200);
    lv_obj_set_x(ui_TabViezhinengai3, 60);
    lv_obj_set_y(ui_TabViezhinengai3, 21);
    lv_obj_set_align(ui_TabViezhinengai3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TabViezhinengai3, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_TabViezhinengai3, LV_OBJ_FLAG_SCROLLABLE);

    ui_Imageyingyuqimeng = lv_img_create(ui_yingyuqimeng);
    kid_content_image_style(ui_Imageyingyuqimeng);
    lv_obj_add_flag(ui_Imageyingyuqimeng, LV_OBJ_FLAG_ADV_HITTEST);

    lv_obj_add_event_cb(ui_Btnrenshizimu, ui_event_Btnrenshizimu, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Btnquweidanci, ui_event_Btnquweidanci, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Btnfanhuizhuye5, ui_event_Btnfanhuizhuye5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_yingyuqimeng, ui_event_yingyuqimeng, LV_EVENT_ALL, NULL);
}
