// This file was generated by SquareLine Studio, then restyled for the kid UI.

#include "../ui.h"
#include "../ui_kid_style.h"

void ui_yuwenbaozang_screen_init(void)
{
    ui_yuwenbaozang = lv_obj_create(NULL);
    kid_screen_style(ui_yuwenbaozang);

    ui_Bg4 = lv_obj_create(ui_yuwenbaozang);
    lv_obj_set_width(ui_Bg4, 464);
    lv_obj_set_height(ui_Bg4, 256);
    lv_obj_set_align(ui_Bg4, LV_ALIGN_CENTER);
    kid_card_style(ui_Bg4, 0xFFFFFF, 0xE7EEF5);

    kid_page_title(ui_yuwenbaozang, &ui_LabelTitle4, "语文宝藏");

    ui_Btnguoxuetangshi = lv_btn_create(ui_yuwenbaozang);
    kid_list_btn(ui_Btnguoxuetangshi, &ui_Label16, "国学唐诗", 16, 116, 126);
    lv_obj_add_flag(ui_Btnguoxuetangshi, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_HIDDEN);

    ui_Btnsanzijing = lv_btn_create(ui_yuwenbaozang);
    kid_list_btn(ui_Btnsanzijing, &ui_Label17, "三字经", 16, 166, 126);
    lv_obj_add_flag(ui_Btnsanzijing, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_HIDDEN);

    ui_Btnfanhuizhuye3 = lv_btn_create(ui_yuwenbaozang);
    kid_small_back_btn(ui_Btnfanhuizhuye3, &ui_Label18);

    ui_TabViezhinengai1 = lv_tabview_create(ui_yuwenbaozang, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_TabViezhinengai1, 300);
    lv_obj_set_height(ui_TabViezhinengai1, 200);
    lv_obj_set_x(ui_TabViezhinengai1, 60);
    lv_obj_set_y(ui_TabViezhinengai1, 21);
    lv_obj_set_align(ui_TabViezhinengai1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TabViezhinengai1, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_TabViezhinengai1, LV_OBJ_FLAG_SCROLLABLE);

    ui_Imageyuwenbaozang = lv_img_create(ui_yuwenbaozang);
    kid_content_image_style(ui_Imageyuwenbaozang);
    lv_obj_add_flag(ui_Imageyuwenbaozang, LV_OBJ_FLAG_ADV_HITTEST);

    lv_obj_add_event_cb(ui_Btnguoxuetangshi, ui_event_Btnguoxuetangshi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Btnsanzijing, ui_event_Btnsanzijing, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Btnfanhuizhuye3, ui_event_Btnfanhuizhuye3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_yuwenbaozang, ui_event_yuwenbaozang, LV_EVENT_ALL, NULL);
}
