// This file was generated by SquareLine Studio, then restyled for the kid UI.

#include "../ui.h"
#include "../ui_kid_style.h"

void ui_zhinengai_screen_init(void)
{
    ui_zhinengai = lv_obj_create(NULL);
    kid_screen_style(ui_zhinengai);

    ui_Bg3 = lv_obj_create(ui_zhinengai);
    lv_obj_set_width(ui_Bg3, 464);
    lv_obj_set_height(ui_Bg3, 256);
    lv_obj_set_align(ui_Bg3, LV_ALIGN_CENTER);
    kid_card_style(ui_Bg3, 0xFFFFFF, 0xE7EEF5);

    kid_page_title(ui_zhinengai, &ui_LabelTitle3, "智能AI");

    ui_Btntonghuagushi = lv_btn_create(ui_zhinengai);
    kid_list_btn(ui_Btntonghuagushi, &ui_Label13, "童话故事", 16, 116, 126);
    lv_obj_add_flag(ui_Btntonghuagushi, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_HIDDEN);

    ui_Btnzhishibaike = lv_btn_create(ui_zhinengai);
    kid_list_btn(ui_Btnzhishibaike, &ui_Label14, "知识百科", 16, 166, 126);
    lv_obj_add_flag(ui_Btnzhishibaike, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_HIDDEN);

    ui_Btnfanhuizhuye2 = lv_btn_create(ui_zhinengai);
    kid_small_back_btn(ui_Btnfanhuizhuye2, &ui_Label15);

    ui_TabViezhinengai = lv_tabview_create(ui_zhinengai, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_TabViezhinengai, 300);
    lv_obj_set_height(ui_TabViezhinengai, 200);
    lv_obj_set_x(ui_TabViezhinengai, 60);
    lv_obj_set_y(ui_TabViezhinengai, 21);
    lv_obj_set_align(ui_TabViezhinengai, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TabViezhinengai, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_TabViezhinengai, LV_OBJ_FLAG_SCROLLABLE);

    ui_Imagezhinengai = lv_img_create(ui_zhinengai);
    kid_content_image_style(ui_Imagezhinengai);
    lv_obj_add_flag(ui_Imagezhinengai, LV_OBJ_FLAG_ADV_HITTEST);

    lv_obj_add_event_cb(ui_Btntonghuagushi, ui_event_Btntonghuagushi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Btnzhishibaike, ui_event_Btnzhishibaike, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Btnfanhuizhuye2, ui_event_Btnfanhuizhuye2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_zhinengai, ui_event_zhinengai, LV_EVENT_ALL, NULL);
}
